### ISSUE TITLE
Implement linear memory model

### ISSUE THREAD

**Issue by ZVasilii** [106-inc/sim2022#27]
Now memory is implemented using `std::unordered map` for simplicity. This model cannot accurately represent real virtual memory, which has to be linear and sequential. New implementation of memory should have "array of bytes" semantics
Additionally, memory interface for instructions `lb`and `lh` etc. should be implemented.

**Comment by Bryanskiy** [comment]
Can you provide any description for this issue? Your aims isn't clearly enough for me.

**Comment by ZVasilii** [comment]
> Can you provide any description for this issue? Your aims isn't clearly enough for me.

Done

**Comment by derzhavin3016** [comment]
I think you should also provide a memory interface to load a range of bytes by start address.
For example:
```c++
template <std::forward_iterator It>
void loadRange(Addr start, It begin, It end);
``` 
Maybe you can add here `requires` clause to check underlying type and/or its size
