### ISSUE TITLE
Too much copypaste in store<Entity> & load<Entity> functions

### ISSUE THREAD

**Issue by ZVasilii** [106-inc/sim2022#57]
Too much copypaste here
Consider using template, e.g. `store<Byte>(addr, byte)` to store byte

_Originally posted by @derzhavin3016 in https://github.com/106-inc/sim2022/pull/43#discussion_r1053054518_

**Comment by ZVasilii** [comment]
- Also add cosimulation func in all store<Entities>

**Comment by derzhavin3016** [comment]
The same issue for loadEntity
